# Generated by Django 4.0 on 2022-04-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.CharField(blank=True, help_text='Ссылка на карту Яндекс Карты с адресом (для контактов)', max_length=255, verbose_name='Ссылка Яндекс Карты')),
                ('togiz', models.CharField(blank=True, help_text='Ссылка на карту 2gis.kz с адресом (для футера)', max_length=255, verbose_name='Ссылка 2gis.kz')),
                ('adress', models.CharField(blank=True, help_text='Без города: Мәңгілік Ел проспект, 45', max_length=255, verbose_name='Адрес')),
                ('work_time', models.CharField(blank=True, max_length=255, verbose_name='Время работы')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('whatsApp', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Контакты для города')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
