# Generated by Django 4.0 on 2022-04-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите город', max_length=255, verbose_name='Город')),
                ('url_name', models.CharField(help_text='Название города в строке браузера (без /)', max_length=255, null=True, verbose_name='URL')),
                ('keywords', models.CharField(blank=True, help_text='Введите текст', max_length=255, null=True, verbose_name='CEO-описание')),
                ('description', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, null=True, verbose_name='CEO-ключевые слова')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Counts_Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Количество',
                'verbose_name_plural': 'Количество',
            },
        ),
        migrations.CreateModel(
            name='ExtraProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('picture', models.ImageField(default='', upload_to='extraproducts/', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Филиал')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Povods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Поводы',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите вопрос', max_length=255, verbose_name='Вопрос')),
                ('text', models.TextField(help_text='Введите ответ', null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Контент вопросов',
                'verbose_name_plural': 'Контент вопросов',
            },
        ),
        migrations.CreateModel(
            name='TextName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Название',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(choices=[('Клиент', 'Клиент'), ('Админ', 'Админ')], default='Родитель', max_length=255, verbose_name='Должность')),
                ('city', models.ForeignKey(blank=True, help_text='Для админа укажите его город', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Город')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.filial', verbose_name='Филиал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TextDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Для города')),
                ('description', models.ManyToManyField(related_name='content_description', to='mainapp.TextContent', verbose_name='Контент вопросов')),
            ],
            options={
                'verbose_name': 'Блок вопросов',
                'verbose_name_plural': 'Блок вопросов',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('ready', models.BooleanField(default=False, verbose_name='Готовый букет')),
                ('comp', models.BooleanField(default=False, verbose_name='Композиции')),
                ('enable', models.BooleanField(default=True, verbose_name='Активный')),
                ('valentine', models.BooleanField(default=False, verbose_name='8 март')),
                ('stock', models.BooleanField(default=False, help_text='При активации акции не забудьте указать процент скидки.', verbose_name='Акция')),
                ('start_stock', models.DateField(blank=True, help_text='Дату старта и конца акции можно не указывать.', null=True, verbose_name='Старт акции')),
                ('end_stock', models.DateField(blank=True, null=True, verbose_name='Конец акции')),
                ('percent_stock', models.PositiveIntegerField(verbose_name='Процент скидки')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ManyToManyField(related_name='category_flowers', to='mainapp.Category', verbose_name='Категория')),
                ('city', models.ManyToManyField(related_name='city_flowers', to='mainapp.City', verbose_name='Города')),
                ('count_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.counts_flowers', verbose_name='Количество')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.filial', verbose_name='Филиал')),
                ('povod', models.ManyToManyField(related_name='povods_flowers', to='mainapp.Povods', verbose_name='Поводы')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='FlowerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flower/', verbose_name='Картина')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.flowers', verbose_name='Цветы')),
            ],
            options={
                'verbose_name': 'Картины',
                'verbose_name_plural': 'Картины',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Стоимость доставки')),
                ('delivery_city', models.TextField(blank=True, null=True, verbose_name='Стоимость доставки по городу:')),
                ('delivery_regions', models.TextField(blank=True, null=True, verbose_name='Стоимость доставки в регионы:')),
                ('delivery_time', models.TextField(blank=True, null=True, verbose_name='Время доставки:')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Для города')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers')),
            ],
            options={
                'verbose_name': 'Корзина продукта',
                'verbose_name_plural': 'Корзина продукта',
            },
        ),
        migrations.CreateModel(
            name='CartExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.PositiveIntegerField()),
                ('cart_in', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.extraproducts')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers')),
            ],
            options={
                'verbose_name': 'Корзина экстра продукта',
                'verbose_name_plural': 'Корзина экстра продукта',
            },
        ),
    ]
