# Generated by Django 4.0 on 2022-04-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_extraproducts_options_setsextraproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartextra',
            name='cart_in',
        ),
        migrations.RemoveField(
            model_name='cartextra',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='cartextra',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='city',
        ),
        migrations.RemoveField(
            model_name='textdescription',
            name='city',
        ),
        migrations.RemoveField(
            model_name='textdescription',
            name='description',
        ),
        migrations.DeleteModel(
            name='TextName',
        ),
        migrations.AlterModelOptions(
            name='setsextraproducts',
            options={'verbose_name': 'Допы Сеты', 'verbose_name_plural': 'Допы Сеты'},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartExtra',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.DeleteModel(
            name='TextDescription',
        ),
    ]
