# Generated by Django 4.0 on 2022-04-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_cartextra_cart_in_remove_cartextra_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers')),
            ],
            options={
                'verbose_name': 'Корзина продукта',
                'verbose_name_plural': 'Корзина продукта',
            },
        ),
        migrations.CreateModel(
            name='CartExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.PositiveIntegerField()),
                ('cart_in', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.extraproducts')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers')),
            ],
            options={
                'verbose_name': 'Корзина экстра продукта',
                'verbose_name_plural': 'Корзина экстра продукта',
            },
        ),
    ]
