# Generated by Django 4.0 on 2022-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_cart_cartproduct_cartextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartextra',
            name='cart_in',
        ),
        migrations.RemoveField(
            model_name='cartextra',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='cartextra',
            name='flower',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='flower',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartExtra',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
