# Generated by Django 4.0 on 2022-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_cartextra_cart_in_remove_cartextra_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsextraproducts',
            name='extra',
            field=models.ManyToManyField(related_name='extra_poducts', to='mainapp.ExtraProducts', verbose_name='Доп'),
        ),
    ]
