# Generated by Django 4.0 on 2022-04-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_setsextraproducts_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='set',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.setsextraproducts', verbose_name='Сет допов'),
        ),
    ]
