# Generated by Django 4.0 on 2022-04-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_flowers_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowers',
            old_name='set',
            new_name='set_dops',
        ),
    ]
