# Generated by Django 4.0 on 2022-04-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_set_flowers_set_dops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowers',
            old_name='set_dops',
            new_name='set',
        ),
    ]
