# Generated by Django 4.0 on 2022-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_extraproducts_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproducts',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
