# Generated by Django 4.0 on 2022-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_extraproducts_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproducts',
            name='col',
            field=models.PositiveIntegerField(default=1, verbose_name='техническое поле, не трогать'),
        ),
        migrations.AlterField(
            model_name='extraproducts',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='техническое поле, не трогать'),
        ),
        migrations.AlterField(
            model_name='extraproducts',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='техническое поле, не трогать'),
        ),
    ]
