# Generated by Django 4.0 on 2022-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_flowers_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='техническое поле, не трогать'),
        ),
    ]
