# Generated by Django 4.0 on 2022-04-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('recipient_phone', models.CharField(max_length=255, verbose_name='Телефон получателя')),
                ('adres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.CharField(choices=[('В течение дня', 'В течение дня'), ('C 07:00 до 09:30', 'C 07:00 до 09:30'), ('До обеда', 'До обеда'), ('13:00-16:00', '13:00-16:00'), ('16:00-19:00', '16:00-19:00'), ('В 23:59', 'В 23:59')], max_length=255, verbose_name='Время')),
                ('anonim', models.BooleanField(default=False, verbose_name='Анонимно')),
                ('sended_phone', models.CharField(max_length=255, verbose_name='Телефон отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('postcard', models.TextField(blank=True, null=True, verbose_name='Открытка')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('paired', models.CharField(choices=[('Оплата наличными курьеру', 'Оплата наличными курьеру'), ('Оплата через Kaspi', 'Оплата через Kaspi'), ('Онлайн оплата', 'Онлайн оплата')], max_length=255, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Оплачен', 'Оплачен'), ('Не оплачен', 'Не оплачен'), ('Завершен', 'Завершен'), ('Собран', 'Собран'), ('В пути', 'В пути'), ('Возврат', 'Возврат'), ('Нереализован', 'Нереализован'), ('Доставлен', 'Доставлен')], default='Новый', max_length=255, verbose_name='Статус')),
                ('sum_result', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('archiv', models.BooleanField(default=False, verbose_name='В архиве')),
                ('like_flower', models.CharField(choices=[('Букет не собран', 'Букет не собран'), ('Букет собран', 'Букет собран'), ('Клиент подтвердил', 'Клиент подтвердил'), ('Клиент не подтвердил', 'Клиент не подтвердил'), ('Заказ доставлен', 'Заказ доставлен')], default='Букет не собран', max_length=255, verbose_name='Фото букета')),
                ('city', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Город')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.filial', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date_add'],
            },
        ),
        migrations.CreateModel(
            name='OrderKurierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='ready_flower')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Корзина курьера',
                'verbose_name_plural': 'Фото курьера',
            },
        ),
        migrations.CreateModel(
            name='OrderFlowerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='ready_flower')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Фото букета',
                'verbose_name_plural': 'Фото букета',
            },
        ),
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.extraproducts')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Корзина продукта',
                'verbose_name_plural': 'Корзина продукта',
            },
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_price', models.PositiveIntegerField(verbose_name='Сумма цветов')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers', verbose_name='Цветы')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='FasrOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавление')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Город')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.filial', verbose_name='Филиал')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.flowers', verbose_name='Цветы')),
            ],
            options={
                'verbose_name': 'Быстрая заявка',
                'verbose_name_plural': 'Быстрая заявка',
                'ordering': ['-date_add'],
            },
        ),
    ]
