# Generated by Django 4.0 on 2022-04-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_users_name_users_phone'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paired',
            field=models.CharField(choices=[('Оплата наличными курьеру', 'Оплата наличными курьеру'), ('Оплата через Kaspi', 'Оплата через Kaspi'), ('Оплата онлайн', 'Оплата онлайн')], max_length=255, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(choices=[('В течение дня', 'В течение дня'), ('7:00-10:00', '7:00-10:00'), ('10:00-13:00', '10:00-13:00'), ('13:00-16:00', '13:00-16:00'), ('16:00-19:00', '16:00-19:00'), ('19:00-22:00', '19:00-22:00')], max_length=255, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_flowers', to='mainapp.flowers', verbose_name='Цветы'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заявка'),
        ),
    ]
