# Generated by Django 4.0 on 2022-04-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_setsextraproducts_extra'),
        ('orders', '0002_alter_order_paired_alter_order_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_items',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='order_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_flowers', to='mainapp.flowers', verbose_name='Букет'),
        ),
        migrations.CreateModel(
            name='Order_items_extra_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='mainapp.extraproducts', verbose_name='Доп')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.order_items', verbose_name='Заказанный букет')),
            ],
            options={
                'verbose_name': 'Допы',
                'verbose_name_plural': 'Допы',
            },
        ),
    ]
